[2022-06-27 19:20:57,001] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\HPr\\Documents\\project\\Ml_Projekt\\housing\\artifact')
[2022-06-27 19:20:57,001] root - ERROR - Error occured in script: [C:\Users\HPr\Documents\project\Ml_Projekt\housing\pipeline\pipeline.py] at line number: [52] error message: [Error occured in script: [C:\Users\HPr\Documents\project\Ml_Projekt\housing\pipeline\pipeline.py] at line number: [24] error message: [Error occured in script: [C:\Users\HPr\Documents\project\Ml_Projekt\housing\config\configuration.py] at line number: [69] error message: [__new__() got an unexpected keyword argument 'dataset_download_url']]]
