[2022-06-27 19:56:18,806] root - INFO - Training pipleine config: TrainingPipelineConfig(artifact_dir='C:\\Users\\HPr\\Documents\\project\\Ml_Projekt\\housing\\artifact')
[2022-06-27 19:56:18,806] root - ERROR - 
        Error occured in script: 
        [ C:\Users\HPr\Documents\project\Ml_Projekt\housing\pipeline\pipeline.py ] at 
        try block line number: [46] and exception block line number: [52] 
        error message: [
        Error occured in script: 
        [ C:\Users\HPr\Documents\project\Ml_Projekt\housing\pipeline\pipeline.py ] at 
        try block line number: [21] and exception block line number: [24] 
        error message: [
        Error occured in script: 
        [ C:\Users\HPr\Documents\project\Ml_Projekt\housing\config\configuration.py ] at 
        try block line number: [62] and exception block line number: [70] 
        error message: [__new__() got an unexpected keyword argument 'dataset_download_url']
        ]
        ]
        
